"""empty message

Revision ID: 642fd95567df
Revises: 
Create Date: 2022-07-27 14:26:15.649893

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '642fd95567df'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('lga', 'state_id',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=True,
               existing_server_default=sa.text('0'))
    op.alter_column('lga', 'lga_name',
               existing_type=mysql.VARCHAR(length=50),
               nullable=True,
               existing_server_default=sa.text("''"))
    op.alter_column('state', 'state_name',
               existing_type=mysql.VARCHAR(length=75),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('state', 'state_name',
               existing_type=mysql.VARCHAR(length=75),
               nullable=True)
    op.alter_column('lga', 'lga_name',
               existing_type=mysql.VARCHAR(length=50),
               nullable=False,
               existing_server_default=sa.text("''"))
    op.alter_column('lga', 'state_id',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=False,
               existing_server_default=sa.text('0'))
    op.create_index('cooment_guest', 'comments', ['comment_guest'], unique=False)
    # ### end Alembic commands ###
